id: dsq-747521269
date: 2007-11-06T00:24:40.0000000-08:00
name: Joe
avatar: https://disqus.com/api/users/avatars/Joe.jpg
message: <p>This seems to fall over when using the cache object.<br>In one unit test, I add an item to the cache, and in another I try to  add the item again, but it already exists.<br>For example when running the following tests together , one will pass and one will fail.  When running them one at a time, both will pass.<br>[Test]<br>public void Add_Item_To_Cache()<br>{<br>  using (new HttpSimulator("/", @"c:\inetpub\").SimulateRequest())<br>  {<br>    Assert.IsTrue(HttpContext.Current.Cache.Count == 0, "Cache should be empty");<br>    HttpContext.Current.Cache.Add("myKey", "myObject", null, DateTime.Now.AddHours(1), System.Web.Caching.Cache.NoSlidingExpiration, System.Web.Caching.CacheItemPriority.Low, null);<br>    Assert.IsTrue(HttpContext.Current.Cache.Count == 1, "Cache should have an item");<br>  }<br>}<br>[Test]<br>public void Add_Item_To_Cache_Again()<br>{<br>  using (new HttpSimulator("/", @"c:\inetpub\").SimulateRequest())<br>  {<br>    Assert.IsTrue(HttpContext.Current.Cache.Count == 0, "Cache should be empty");<br>    HttpContext.Current.Cache.Add("myKey", "myObject", null, DateTime.Now.AddHours(1), System.Web.Caching.Cache.NoSlidingExpiration, System.Web.Caching.CacheItemPriority.Low, null);<br>    Assert.IsTrue(HttpContext.Current.Cache.Count == 1, "Cache should have an item");<br>  }<br>}<br>       <br></p>
